name: test

on:
  push:
  pull_request:
  schedule:
    - cron: '13 15 * * 0'  # 13:15 every Sunday

jobs:
  build_and_test_plugin:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: src

    - name: Pre check
      run: python ./src/devel/check.py

    - name: Install plugin
      run: pip install ./src/pypkgs/ncrystal-plugin-WaterData

    - name: Install ncrystal
      run: pip install "ncrystal-python>=3.9.87" "ncrystal-core>=3.9.87"
    #FIXME: Update to simply:
    # run: pip install "ncrystal>=3.9.87"

    - name: pip list
      run: pip list

    - name: pip check
      run: pip check

    - name: Verify plugin loading
      run: ncrystal-pluginmanager --test WaterData

    - name: Use data file explicitly
      run: nctool -d 'plugins::WaterData/LiquidHeavyWaterD2O_T350.0K.ncmat'
